// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	interaction "douyin/internal/handler/interaction"
	message "douyin/internal/handler/message"
	relation "douyin/internal/handler/relation"
	user "douyin/internal/handler/user"
	video "douyin/internal/handler/video"
	"douyin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user",
				Handler: user.GetUserHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/feed",
				Handler: video.ListVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/publish/action",
				Handler: video.UploadVideoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/publish/list",
				Handler: video.ListVideoByUserHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/favorite/action",
				Handler: interaction.FavoriteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/favorite/list",
				Handler: interaction.ListFavoriteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comment/action",
				Handler: interaction.CommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comment/list",
				Handler: interaction.ListCommentHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/relation/action",
				Handler: relation.FollowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/relation/follow/list",
				Handler: relation.ListFollowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/relation/follower/list",
				Handler: relation.ListFollowerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/relation/friend/list",
				Handler: relation.ListFriendHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/message/action",
				Handler: message.SendMessageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/message/chat",
				Handler: message.ListMessageHandler(serverCtx),
			},
		},
	)
}
